# -*- coding: utf-8 -*-
"""data cleaning using pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K8RD6DAV4Zvb36esFOCgSG-ct6K1LZL2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## **Reading the data from CSV :**"""

df=pd.read_csv('student_habits_performance.csv')
df.shape

"""# **Data Overview :**"""

df.columns

df.dtypes

df.head(10)

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

def data_info(data):

    """
    This function returns a DataFrame containing the summary information for each column
    """

    Names=[col for col in data]
    data_types=[data[col].dtype for col in data.columns]
    top_10_unique_values=[data[col].value_counts().head(10).index.to_list() for col in data.columns]
    nunique_values=[data[col].nunique() for col in data.columns]
    nulls=[data[col].isnull().sum() for col in data.columns]
    percent_of_Nulls= [data[col].isnull().sum()/len(data)*100 for col in data.columns]


    info_df=pd.DataFrame({'Name':Names,
                          'Data_Type':data_types,
                          'Top_10_Unique_Values':top_10_unique_values,
                          'Nunique_Values':nunique_values,
                          'Nulls':nulls,
                          'Percent_of_Nulls':percent_of_Nulls,
                          })
    return info_df

data_info(df)

"""# **Filling column containing nulls:**"""

print(df['parental_education_level'].mode()[0])
df['parental_education_level'].fillna(df['parental_education_level'].mode()[0],inplace=True)
print(df['parental_education_level'].isna().sum())


"""parental_education_level contained 91 missing values (9.1%). Since this is a categorical feature
   and 9.1% of the values is too much to drop -> missing values were replaced using the mode, which was (High School) .
"""

df['parental_education_level']

"""# **Constructuing a new feature:**"""

df['total_screen_time']=df['social_media_hours'] + df['netflix_hours']
df['total_screen_time']

for col in ['study_hours_per_day','social_media_hours','netflix_hours',
            'sleep_hours','attendance_percentage','exam_score']:
    Q1, Q3 = df[col].quantile([0.25, 0.75])
    IQR = Q3 - Q1
    out = df[(df[col] < Q1 - 1.5*IQR) | (df[col] > Q3 + 1.5*IQR)]
    print(col, len(out))

plt.boxplot(df['study_hours_per_day'])
plt.title('distribution of study hours per day')
plt.show()

plt.boxplot(df['social_media_hours'])
plt.title('distribution of social media hours')
plt.show()

plt.boxplot(df['netflix_hours'])
plt.title('distribution of netflix hours')
plt.show()

plt.boxplot(df['sleep_hours'])
plt.title('distribution of netflix hours')
plt.show()

print(df[['exam_score', 'attendance_percentage']].agg(['min', 'max']))
print((df[['study_hours_per_day','social_media_hours','netflix_hours','sleep_hours']] < 0).sum())

(df['exam_score'] < 100).value_counts()
" there are 48 person of 1000 who scored 100 in the exam ! "

(df['exam_score']<50).value_counts()
" there are 131 person who failed in the exam scoring less than 50 degrees !"

(df['exam_score']==50).value_counts()
"no one got exactly the half score !"

df['total_hours'] = (df['study_hours_per_day'] + df['social_media_hours']
                       + df['netflix_hours'] + df['sleep_hours'])
(df['total_hours'] >= 12).sum()
"most of the students (832 student from 1000 one) spends half of the day or more studying , sleeping or on social media !"

print((df['attendance_percentage']==100).sum())


print((df['attendance_percentage']==0).sum())


" 66 students have attended all the sessions !"
" all students have attended at least one time ! "

(df['gender']).value_counts()

(df['parental_education_level']).value_counts()

(df['internet_quality']).value_counts()

(df['diet_quality']).value_counts()

"""**Encoding the categorical data (for preprocessing not cleaning):**"""

df.shape

df.head()

df.isnull().sum()

df.duplicated().sum()

df.describe()

df

df.to_csv('student_habits_cleaned.csv', index=False)